FROM node:lts-alpine AS backend

ENV PORT=3000
EXPOSE 3000

WORKDIR /src

COPY package.json /src/package.json
COPY package-lock.json /src/package-lock.json
RUN npm ci

HEALTHCHECK --interval=30s CMD node healthcheck.ts

COPY . /src/

CMD ["npm", "start"]